### ISSUE TITLE
WP_AdminBar cache actions not working

### ISSUE THREAD

**Issue by jphorn** [Servebolt/servebolt-optimizer#213]
All three "Purge cache" actions in WP_AdminBar don't seem to do anything. From discussion with Remkus I understand they should open a modal/popup with further action, but this won't work for me. The URL just ends with a hashbang (#) upon click. This is in back-end (wp-admin) or front-end (from any article).

I'm experiencing this in both Safari/macOS/latest (`14.1.1 (16611.2.7.1.4)`) and Chrome/macOS/latest (`91.0.4472.77`). No console errors apart from two (unrelated) errors for a misconfigured display ad.

![CleanShot 2021-06-09 at 10 07 38@2x](https://user-images.githubusercontent.com/478156/121331451-2ceb9700-c917-11eb-82f7-29466821db12.png)

---
<details>
<summary> _Quick screencast_ </summary>
<br>

![https://cln.sh/9DTnka](https://cln.sh/9DTnka+)

</details>

**Comment by thoaud** [comment]
@jphorn thanks for the report!

Have you tried the Use native JS fallback?
It can be found in the general settings of the plugin.

**Comment by jphorn** [comment]
Just enabled that setting and seems to work now in the backend (with native UI prompts), but not from frontend. Again -- no console errors unfortunately.

**Comment by roberts91** [comment]
Do you get any errors in the developer console? I suspect this might be in relation to other plugins, maybe even a conflict of some sort.

**Comment by jphorn** [comment]
> Again -- no console errors unfortunately.

See also screencast in first post. Nothing is shown in console.

**Comment by roberts91** [comment]
I'm sorry, I did not see that one. Okay, if there are no errors then the script-files are not likely loaded. Can you check the source code (while logged in) and look for the file "cloudflare-cache-purge-trigger.js"?

**Comment by jphorn** [comment]
Hmm. I don't see that file included. Not when searching for its file name, or in the scripts overview.

![CleanShot 2021-06-09 at 14 34 04](https://user-images.githubusercontent.com/478156/121355216-f2dabf00-c92f-11eb-9f59-2b75b2d9c6c6.png)

**Comment by roberts91** [comment]
Okay, then that is most def. part of the issue. I'm not seeing why this is happening tho, and hard to figure out without going hands on.

**Comment by roberts91** [comment]
v3.0.1 should solve this issue. Thanks for reporting. Closing.
