### ISSUE TITLE
wp-cli command "servebolt db analyze" crashes in multisite installations

### ISSUE THREAD

**Issue by erlendeide** [Servebolt/servebolt-optimizer#28]
$ wp servebolt db analyze

PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function wpdb::prepare(), 1 passed in public/wp-content/plugins/servebolt-optimizer/admin/optimize-db/transients-cleaner.php on line 97 and exactly 2 expected in public/wp-includes/wp-db.php:1222
Stack trace:
#0 public/wp-content/plugins/servebolt-optimizer/admin/optimize-db/transients-cleaner.php(97): wpdb->prepare('SELECT blog_id ...')
#1 public/wp-content/plugins/servebolt-optimizer/servebolt-optimizer.php(108): servebolt_analyze_tables(true)
#2 [internal function]: WP_CLI\Runner->{closure}(Array, Array)
#3 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(89): call_user_func(Object(Closure), Array, Array)
#4 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#5 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(421): call_user_func(Object(Closure), Array, Array)
#6 phar: in public/wp-includes/wp-db.php on line 1222
Fatal error: Uncaught ArgumentCountError: Too few arguments to function wpdb::prepare(), 1 passed in public/wp-content/plugins/servebolt-optimizer/admin/optimize-db/transients-cleaner.php on line 97 and exactly 2 expected in public/wp-includes/wp-db.php:1222
Stack trace:
#0 public/wp-content/plugins/servebolt-optimizer/admin/optimize-db/transients-cleaner.php(97): wpdb->prepare('SELECT blog_id ...')
#1 public/wp-content/plugins/servebolt-optimizer/servebolt-optimizer.php(108): servebolt_analyze_tables(true)
#2 [internal function]: WP_CLI\Runner->{closure}(Array, Array)
#3 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(89): call_user_func(Object(Closure), Array, Array)
#4 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#5 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(421): call_user_func(Object(Closure), Array, Array)
#6 phar: in public/wp-includes/wp-db.php on line 1222

**Comment by thoaud** [comment]
Fixed in v1.5
