### ISSUE TITLE
Purge cache for custom types

### ISSUE THREAD

**Issue by ZeroX66** [Servebolt/servebolt-optimizer#428]
Hi there,

In "Automatic purge on update" under tab cache purging it would be nice if custom types can be purged too auto.

/Regards, Micke

**Comment by oskibri** [comment]
Hey @ZeroX66!

Automatic purging of custom types is already something that is implemented in the plugin. As long as the post ID belong to a custom post type which has the status "public" it will be treated as any old post and purging should work as expected. 

Hope that helps!

Kind regards
Oskar Voldbakken Hesle
----
Technical Support Engineer - EMEA
[Servebolt Support](https://servebolt.com/)

**Comment by andykillen** [comment]
@ZeroX66, I've tested this one various systems with custom post types without issue.  It would be good to speak with support if you are still seeing this error.
