### ISSUE TITLE
Way to hide the Plugin from the Toolbar and Editor

### ISSUE THREAD

**Issue by swissky** [Servebolt/servebolt-optimizer#429]
Hey, is there a way to hide the Plugin from the Admin Toolbar and the Sidebar in the Editor. We need this for our clients. For the Admin Navigation, we use the User Role Plugin, but the other places don't get hidden when we hide the Navigation Menu for a specific User Role.

**Comment by pdaalder** [comment]
Yes there is! Quickest and easiest would be to use this code/plugin: https://gist.github.com/andykillen/75f2d11d80ae17cf73a185a7d08b06af

**Comment by swissky** [comment]
Thank you
