### ISSUE TITLE
Ways to use Prefetch and Image Resize function without AD

### ISSUE THREAD

**Issue by swissky** [Servebolt/servebolt-optimizer#430]
Hey, we have our own CF Enterprise Account and would like to use Prefetch and Image Resize from your Plugin, but with the Option to delete the Cache from our Cloudflare Account. Is there any Option to open it?

Thank you

**Comment by pdaalder** [comment]
Hey Kevin, I'm afraid that won't be possible since those features are only available for clients using Accelerated Domains. You're free to use our existing codebase from this plugin for whatever you need, as described in the license.
