### ISSUE TITLE
Uncaught ReferenceErorr: woocommerce_admin is not defined

### ISSUE THREAD

**Issue by martinowren** [Servebolt/servebolt-optimizer#51]
![image](https://user-images.githubusercontent.com/22822433/78986033-99f47880-7b2a-11ea-9027-5cb2afc66007.png)
The bug is triggered on the Servebolt Plugin Menu -> Cloudflare Cache.

**Comment by roberts91** [comment]
Hello Martin! Are you sure that file is related to our plugin? I'm not aware of a file with that filename in our source code.

Kind regards,
Robert
