### ISSUE TITLE
The version of Guzzle in your vendor dependencies (current master branch 6.5.2) is broken. FYI

### ISSUE THREAD

**Issue by monarchhf** [Servebolt/servebolt-optimizer#52]
I ran across this issue when activating a plugin on my site, which I have hosted with your company.  

On activation the plugin generated this error: 

`PHP` `Fatal error: Uncaught Error: Call to undefined function GuzzleHttp\\_idn_uri_convert() in /kunder/monarc_5574/monarc_7528/public/wp-content/plugins/servebolt-optimizer/vendor/guzzlehttp/guzzle/src/Client.php:220`

Turns out, this is because in 6.5.2 - `_idn_uri_convert` is undefined.  
This thread covers the topic in depth: 
https://github.com/guzzle/guzzle/issues/2511

This is where you can see this function is undefined: 
https://github.com/guzzle/guzzle/issues/2511#issuecomment-585962969

Confirmation that 6.5.0 does not have this issue: 
https://github.com/guzzle/guzzle/issues/2511#issuecomment-573997688

And here's a fix that can be added to the composer json file: 
https://github.com/guzzle/guzzle/issues/2511#issuecomment-586013514

**Comment by roberts91** [comment]
Hello!
This is actually not an issue of a broken vendor-folder, but more about an issue where multiple plugins are using the same Composer-packages at different versions. This gives an unfortunate cocktail-effect in the plugin-ecosystem of Wordpress. We've seen this especially with GuzzleHttp (v5/6/7).

That being said - this issue will be solved in the upcoming v2.2.0. I would recommend you try this version, and feel free to re-open this issue if the problem persists.

Kind regards,
Robert
