### ISSUE TITLE
Conflict Issues with WooFunnels OrderBump

### ISSUE THREAD

**Issue by Cion3** [Servebolt/servebolt-optimizer#66]
Please see the video below 
https://www.loom.com/share/c83f073b78444cd6a0fc3069ed456baa

Thanks!

**Comment by roberts91** [comment]
Hello! Sorry for the late reply. The URL you sent unfortunately gave me a 404. In regards of conflicts - we've had some issue with our composer-dependencies being in conflicts with other plugins. This will be corrected in the upcoming release of v2.2.0. I would recommend you to test with this version and see if the issue persist. If it does then please feel free to write.
