### ISSUE TITLE
CSS conflict with the Gutenberg sidebar and Rank Math Sidebar

### ISSUE THREAD

**Issue by surajv** [Servebolt/servebolt-optimizer#70]
It looks like the latest update broke the styling of the Gutenberg and our Rank Math SEO's sidebar. The text is centrally aligned. Here is the screenshot:

<img width="1123" alt="Markup 2020-09-27 at 23 42 56" src="https://user-images.githubusercontent.com/1798877/94372453-40552a00-011b-11eb-871f-df92f65fc6fc.png">

![Markup on 2020-09-27 at 23:44:35](https://user-images.githubusercontent.com/1798877/94372469-6da1d800-011b-11eb-8997-72c0ff783b93.png)

**Comment by roberts91** [comment]
Hello Suraj, and thanks for reporting this. This looks like its related to the styling of the cache purge buttons. I need to make sure that the styling is sufficiently targeted. I'll create a ticket in our system and track it from there. Will get back to you when I know more.

Kind regards,
Robert

**Comment by roberts91** [comment]
Looking through the changelog I see that this bug was indeed caused by our plugin, but it occurred in previous versions of the plugin (pre v2.1.3). So this should not be present from v2.1.3 and forward. Please let me know if that's not the case in your end.
