### ISSUE TITLE
undefined constant Servebolt_Nginx_Fpc

### ISSUE THREAD

**Issue by thoaud** [Servebolt/servebolt-optimizer#9]
```Warning: Use of undefined constant Servebolt_Nginx_Fpc - assumed 'Servebolt_Nginx_Fpc' (this will throw an Error in a future version of PHP) in /srv/users/serverpilot/apps/wordpress/public/wp-content/plugins/servebolt-optimizer/servebolt-optimizer.php on line 20```

**Comment by erlendeide** [comment]
Fixed in develop
